### ISSUE TITLE
Internal audit of the smart contract

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#134]
# Internal audit Part 1

21st November
Participants: @loredanacirstea, @czepluch, @ice09 

**Scope:**
- https://github.com/raiden-network/microraiden/blob/master/contracts/contracts/RaidenMicroTransferChannels.sol
- Contract versioning PR https://github.com/raiden-network/microraiden/pull/156
- ECVerify refactor PR https://github.com/raiden-network/microraiden/pull/157

**Agenda**: go through the contracts code and PRs for an overview and discussions

**Outcome:**
1. improve `settleChannel` logic, get rid of `min()` & `max()` -> fixed https://github.com/raiden-network/microraiden/pull/163 
2. change `close` to `cooperativeClose` & `uncooperativeClose` -> fixed https://github.com/raiden-network/microraiden/pull/163 
3. code_style & comment fixes -> fixed https://github.com/raiden-network/microraiden/pull/163 
4. ECVerify.sol - use `address signature_address` instead of `var addr` -> fixed in https://github.com/raiden-network/microraiden/commit/be16aa245eb5766609ecd588a6988b9b8225896b

5. `_sender` to `_sender_address` & similar (not changing this for now in events because -> python code refactor; leaving for future release); -> fixed https://github.com/raiden-network/microraiden/pull/163 
6. possible issues with `uint192(_deposit)` - `_deposit` is `uint256`
https://github.com/raiden-network/microraiden/blob/1f175393c604a7b682374110690d25790a7e7808/contracts/contracts/RaidenMicroTransferChannels.sol#L217 -> fixed in https://github.com/raiden-network/microraiden/pull/204

7. document `memcpy`, `concat` - taken from https://github.com/Arachnid/solidity-stringutils/blob/master/strings.sol for temporary use until we can implement `eth_signTypedData`
fixed (removed it) https://github.com/raiden-network/microraiden/pull/176

**Comment by LefterisJP** [comment]
For the versioning PR I left some comments in a new issue along with a proposal: https://github.com/raiden-network/microraiden/issues/162

**Comment by berndbohmeier** [comment]
## Internal Audit Part 2
Participants: Bernd Bohmeier

#### scope:
https://github.com/raiden-network/microraiden/blob/master/contracts/contracts/RaidenMicroTransferChannels.sol

Overall the contract is in a good shape. Most stuff I found is styling wise and you could have different opinion on it. So I will just mention there what I noticed, and you can then think about if you see it the same way and change it, or leave it. 
I found one major issue concerning a replay attack which needs discussion!
When I ask a question, I dont need it to be answered. Its more like: If you feel comfortable to answer it, then everything is fine, if not you should do some research. 

#### Biggest issue: verfiyBalanceProof
The balanceProof only consist of: _receiver_address, _open_block_number, _balance. There is no information included on what you are signing, only data. The balanceProof is in this contract already used for 2 things. The sender verifies the new balance and the receiver use this to sign it wants to cooperatively close the channel. This is bad and opens a door for potential replay attacks:
- If any other contract just uses this 3 values for something else (unlikely)
- If there are two channels between address1 and address2 in both directions opened on the same block, they can be used vise versa potential with wrong meaning, if this would be implemented where receiver on the cooperative close is the sender. 
- !!At the moment, the close request is signed by the receiver and the receiving address is the receiver, this message is so not tied to any channel (sender, receiver) and can be used to close any channel with the given receiver!!
fix: Include some kind of message id that encodes the meaning, either cooperativeCloseChannel or balanceProof

#### other stuff
I think the other most critical parts of the contract, where things can go wrong, is all the assembly stuff and the two close functions. So I would spend some work to see if you can make them little better. 

- line 438: mload loads 32 bytes into memory, the variable is only 4 bytes and also b might be shorter, is that safe and why is that save to do? If memory words always start at 32byte the variable should be save but what about b, which might be shorter. 
- line 231: uncooperativeClose and cooperativeClose
  they have overlapping functionality but I think you did refactor that on purpose?
- line 241: if and else with require in it is hard to understand, better:
    ```
        if(msg.sender == _receiver_address) {
            ...
        } else if (msg.sender == sender)  {
           ...
        } else {
         revert();
       }```
- line 272: Why is a balance proof of the sender necessary? By sending in this transaction, it is basically signing all the information, so it should be redundant. 
- line 181: The comment is wrong, there is no padding in data,  see line 451.
- line 183+189:Better write as: 
    ```
   if(length == 20) {
            ...
      } else if (length == 24) {
           ...
      } else {
           revert();
       }
     ```
- line 283: Dont mix in constant function between non constant functions, order them properly as in the solidity style guide suggested (http://solidity.readthedocs.io/en/develop/style-guide.html#order-of-functions)
- line 295: put every return value in own line
- line 44: make order in both struct consistent, so closing_balance should be first
- line 239: Naming is inconsistent sometimes it is sender_address, here it is sender. I'd say sender is totally fine, because the type is address so it is clear, but either way is fine and then definitely make it consistent
- line 27-30 token, channels, closing_requests no visibility (public, private) defined
- natspec: Consider usage of `@notice` in the natspec documentation. This will be shown to the user by supporting wallets on signing(see https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format)
- line 25 `prefix` is not used anywhere
- line 53 `isToken` is not used anywhere
- line 144 verifyBalanceProof can be `pure`

#### Naming convention:
This is just some things I noticed, totally fine if you like it better how it is
- token_address, challenge_period, ... and parameter names _challenge_period does not follow solidity naming conventions, which is tokenAddress, _challengePeriod, ..
- constant variables like `version` do not follow solidity naming convention UPPER_CASE
- event names: If you for example look at erc20 token contract events are usually named after what happend as a noun. It is Transfer and Approval and not Transferred and Approved. So it would be:
ChannelCreation
ChannelTopUp
ChannelCloseRequest
ChannelSettlement

#### other:
Fix the requirements file in contracts, it is not complete, populus and gevent are definitely missing, maybe more. To run the tests I needed the requirements file from the python package.

**Comment by LefterisJP** [comment]
As @berndbohmeier pointed out this:

> !!At the moment, the close request is signed by the receiver and the receiving address is the receiver, > this message is so not tied to any channel (sender, receiver) and can be used to close any channel > with the given receiver!!
> fix: Include some kind of message id that encodes the meaning, either cooperativeCloseChannel or balanceProof

is an urgent reply attack problem and needs addressing. Will you make a PR for it @loredanacirstea or first document in separate specific issue?

**Comment by loredanacirstea** [comment]
@LefterisJP , 
I will make a separate issue, the initial logic was `closing_sig` being `balance_msg_sig` (sender-signed balance proof) signed by the receiver - this was safe. I'm now seeing that I lost this logic at some point.

**Comment by loredanacirstea** [comment]
@berndbohmeier , please check my comment above. If there are things that you consider unsolved / unanswered, please reopen this issue.

I may have misunderstood `line 438: mload loads 32 bytes into memory,.....`. Let me know if you still consider this an issue.
