### ISSUE TITLE
Webui channel balance is increased without a successful payment

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#170]
While testing eth_signTypedData, the channel balance in the webui was increasing even though `verify_balance_proof` from `crypto.py` did not correctly verify the proof -> did not accept the payment. Resource was not provided and `402 (PAYMENT REQUIRED)` was served again.

Please re-test this.

**Comment by andrevmatos** [comment]
This is intended. I was assuming that, as soon as the balance proof is created and sent, it should be considered paid, and that's why I was already incrementing the balance. The problem is, in the current implementation of the paywall, I've no control of after the next request. It sets the balance proof cookies and reload the page, so it's not easy to recover the status of the previous request to, only then, update the balance. Ajax requests are easier, though. I'll think in a way to improve this scenario.

**Comment by loredanacirstea** [comment]
I am pushing for that REST api https://github.com/raiden-network/microraiden/issues/142

The above behavior does not seem correct to me - if anything goes wrong, you make the client lose tokens.
