### ISSUE TITLE
Add withdraw feature, similar to close_all_channels

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#330]
Contract now has a `withdraw` function for the receiver.
```
function withdraw(
        uint32 _open_block_number,
        uint192 _balance,
        bytes _balance_msg_sig)
        external
    {...}
```

As suggested in https://github.com/raiden-network/microraiden/issues/248, a script for withdrawing tokens can be added. Maybe with some parameters such as: time since last withdraw, min number of tokens to withdraw etc.

**Comment by andrevmatos** [comment]
Time since last withdraw would require event parsing and/or storage data. Instead, I implemented a `--minimum-amount` option, which may be used to specify the minimum amount ot tokens available in the channel (taking into account the previous withdraw and currrent balance), to trigger withdraw. It'll withdraw from all channels with valid balance proofs and available tokens at least this amount.
