### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by shaeqahmed** [raiden-network/microraiden#419]
"server won't accept this channel.
Please, close+settle+forget, and open a new channel"

this message is displayed on both chrome and firefox with metamask 3.14.1 on the ropsten test network. it appears after depositing the TKN tokens and trying to sign them.  tried the advice but was not able to fix

**Comment by andrevmatos** [comment]
Thank you for you submission, @shaeqahmed . The issue was not with µRaiden, but a deployment issue caused by our parity node not syncing with ropsten. [Parity 1.9.2](https://github.com/paritytech/parity/releases/tag/v1.9.2) was released specifically to address this issue, and a bump and restart on our server made µRaiden able to see the new events and channels again.

**Comment by theackso** [comment]
The same issue happens for me aswell in Chrome, Chromium and Firefox on Windows & Ubuntu 17.10

**Comment by andrevmatos** [comment]
@theackso thank you for the heads up. Looks like Ropsten went under some weird rollercoaster with Parity these days, which weren't caught on our alert systems. An update+restart of Parity fixed the issue for now, but I suppose this will hunt us for some time still, until we come up with some auto update scheme for our ETH node.
